### ISSUE TITLE
How often does this get built and released?

### ISSUE THREAD

**Issue by echosa** [kelleyk/ppa-emacs#2]
There was recently a fix merged into the emacs-26 branch (and subsequently merged into master as well) that fixes a bug I reported. I'd like to have this fix, but would rather not use the emacs-snapshot PPA. 

How often does this PPA get built and what triggers it? Will this PPA's version of emacs 26 be built again, including the latest code changes?

I'm new to PPAs so I don't fully understand how they work.

**Comment by kelleyk** [comment]
PPAs are Debian-style package repositories hosted by Canonical (the Ubuntu folks); they build new binary packages only when someone uploads new source packages.  Some people have automation set up to automatically do that (e.g. for snapshot or nightly packages).  These are rebuilt only when I manually upload new source packages.

Usually, I wait for stable upstream releases (e.g. 26.2).  Can you provide links to the commits involved and any relevant mailing list discussion?  If the issue is severe enough, I'd consider releasing updated packages.  Otherwise, cherry-picking that patch into this packaging repository and building the packages yourself should not be too hard.
