### ISSUE TITLE
Impish release

### ISSUE THREAD

**Issue by half-adder** [kelleyk/ppa-emacs#20]
`sudo apt-get update` fails when I add your ppa to my sources (and manually putting `[trusted=true]` after `deb` in the `sources.list.d/` file with the following error:
```
E: Failed to fetch http://ppa.launchpad.net/kelleyk/emacs/ubuntu/dists/impish/main/binary-i386/Packages  404  Not Found [IP: 91.189.95.85 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

I assume this is because the package is not targeted to impish?

**Comment by kelleyk** [comment]
A build for Impish hadn't been released, that's right.

It's usually better to stick the PPA's key in a file in `/etc/apt/trusted.gpg.d` rather than mark the sources entry trusted, so that if the key changes unexpectedly, you are alerted.

I've released 28.1 for impish, so I'm going to close this issue; please let me know how it goes!
